backbone_signature: stabilityai/stable-diffusion-xl-base-1.0
vae_num_channels: 4
unet_input_channels: 4
timestep_sampling: custom_timesteps
selected_timesteps: [250, 500, 750, 1000]
prob: [0.25, 0.25, 0.25, 0.25]
conditioning_images_keys: []
conditioning_masks_keys: []
source_key: source_image
target_key: source_image_paste
bridge_noise_sigma: 0.005